apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-commander-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-commander
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_HOSTS
          value: "local:{{ .Release.Name }}-redis-0.{{ .Release.Name }}-redis-db:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-commander-svc
spec:
  type: NodePort
  ports: 
  - port: 8081
    targetPort: 8081

  selector:
    app: {{ .Release.Name }}-redis-commander