apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
spec:
  serviceName: {{ .Release.Name }}-redis-db
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
      annotations: 
        linkerd.io/inject: enabled
        config.linkerd.io/skip-inbound-ports: "6379"
    spec:
      containers:
  
        # --- Контейнер 1: REDIS ---
        - name: redis
          image: redis:7.0-alpine
          # Вставляем ресурсы СЮДА (на уровне name)
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command: ["sh", "-c"]
          args:
            - |
              set -e
              case "$HOSTNAME" in
               *-0)
                echo "I am MASTER"
                docker-entrypoint.sh redis-server --appendonly yes --dir /data
                ;;
               *)
                echo "I am REPLICA"
                docker-entrypoint.sh redis-server --replicaof {{ .Release.Name }}-redis-0.{{ .Release.Name }}-redis-db {{ .Values.redis.port }} --appendonly yes --dir /data
                ;;
              esac
        
       
        # --- Контейнер 2: SENTINEL ---
        - name: redis-sentinel
          image: redis:7.0-alpine
          # И сюда тоже (используем те же ресурсы, что и для редиса)
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          command: 
          - "sh"
          - "-c"
          - |
            mkdir -p /data/sentinel 
            cp /etc/sentinel-ro/sentinel.conf /data/sentinel/sentinel.conf
            redis-sentinel /data/sentinel/sentinel.conf
          ports:
            - containerPort: 26379
              name: sentinel
          volumeMounts:
            - name: sentinel-config
              mountPath: /etc/sentinel-ro
            - name: sentinel-data
              mountPath: /data/sentinel
            
      volumes:
        - name: sentinel-config
          configMap:
            name: {{ .Release.Name }}-redis-sentinel-config
        - name: sentinel-data
          emptyDir: {}
  
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
