apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-redis-db
  labels: 
    app: {{ .Release.Name }}-redis
  annotations: 
    linkerd.io/inject: enabled 
    config.linkerd.io/opaque-ports: "6379"
spec: 
  ports: 
    - port: {{ .Values.redis.port }}
      name: redis 
  publishNotReadyAddresses: true
  clusterIP: None
  selector: 
    app: {{ .Release.Name }}-redis
