apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis-policy

spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-redis 
  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-app 
    ports:
    - protocol: TCP
      port: 6379

  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-redis 
    ports:
    - protocol: TCP
      port: 6379
    - protocol: TCP
      port: 26379